CREATE TABLE IF NOT EXISTS email_jobs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,

  idempotency_key VARCHAR(255) NOT NULL UNIQUE,

  to_email VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,

  scheduled_at DATETIME NOT NULL,

  status ENUM('scheduled', 'sent', 'failed') NOT NULL DEFAULT 'scheduled',

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
